apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: yantra4d

resources:
- namespace.yaml
- yantra4d-backend-deployment.yaml
- yantra4d-backend-service.yaml
- yantra4d-studio-deployment.yaml
- yantra4d-studio-service.yaml
- yantra4d-landing-deployment.yaml
- yantra4d-landing-service.yaml
- yantra4d-redis-pvc.yaml
- yantra4d-redis-deployment.yaml
- yantra4d-redis-service.yaml

images:
- digest: sha256:96ef44d89aeb1e150845b09d8af476a6d0dcece635b752a86e2faeaed8e8ba3c
  name: ghcr.io/madfam-org/yantra4d/backend
  newName: ghcr.io/madfam-org/yantra4d/backend
- digest: sha256:81345de41c07122474eff592ae70005ed78fa961184d4bdd79c3d7bc376a889b
  name: ghcr.io/madfam-org/yantra4d/landing
  newName: ghcr.io/madfam-org/yantra4d/landing
- digest: sha256:8c3469b70229c12b137ac6636d7382b803dbaf94e341d8ef4b386e55b656861a
  name: ghcr.io/madfam-org/yantra4d/studio
  newName: ghcr.io/madfam-org/yantra4d/studio
