apiVersion: v1
kind: Service
metadata:
  name: yantra4d-redis
  labels:
    app.kubernetes.io/name: yantra4d-redis
    app.kubernetes.io/part-of: yantra4d
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: yantra4d-redis
  ports:
    - port: 6379
      targetPort: 6379
      protocol: TCP
